# Assignment-1

In [25]:
# Import necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.spatial import distance

In [26]:
# Loading Iris dataset
from sklearn.datasets import load_iris
iris=load_iris()
x=iris.data[:5] # Take first 5 rows for demo
print('Sample Data:\n',x)

# Select two sample points
point1=x[0]
point2=x[1]

# Euclidean Distance
print("\nEuclidean:", distance.euclidean(point1, point2))

# Manhattan Distance
print("Manhattan:", distance.cityblock(point1, point2))

# Minkowski Distance (p = 3)
print("Minkowski (p=3):", distance.minkowski(point1, point2, p=3))

# Hamming Distance
print("Hamming:", distance.hamming(point1, point2))

# Cosine Distance
print("Cosine Distance:", distance.cosine(point1, point2))

# Cosine Similarity
print("Cosine Similarity:", 1 - distance.cosine(point1, point2))

Sample Data:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

Euclidean: 0.5385164807134502
Manhattan: 0.6999999999999993
Minkowski (p=3): 0.5104468722001463
Hamming: 0.5
Cosine Distance: 0.0014208364959781283
Cosine Similarity: 0.9985791635040219


In [27]:
# Jaccard Distance Demonstration
a = np.array([1, 1, 0, 1, 0])
b = np.array([1, 0, 0, 1, 1])

# Jaccard Distance
jaccard_dist = distance.jaccard(a, b)
print("Jaccard Distance:", jaccard_dist)


Jaccard Distance: 0.5
